spring:
  rabbitmq:
    host: 175.116.181.34
    port: 5672
    username: qaguest
    password: gitrnd!
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://175.116.181.34:5432/opengds_2018?charSet=UTF-8&prepareThreshold=1
    username: postgis
    password: postgis
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 3
      maximum-pool-size: 20
      pool-name: gdoDBPool_Prod
      auto-commit: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  http:
    multipart:
      max-file-size: 10485760KB
      max-request-size: 10485760KB
server:
  port: 8080
  context-path: /geodt
  servlet:
    session:
      timeout: 3600
  error:
    whitelabel:
      enabled: false
gitrnd:
  serverhost: 175.116.181.34
  apache:
    host: 127.0.0.1
    port: 8888
    basedir: gdofiles
    basedrive: C
  rabbitmq:
    exchange: opengds_qa_exchange
    routingKey: opengds_qa_key
mybatis:
  config-location: classpath:config/mybatis.xml
  mapper-location: classpath:sql/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true