spring:
  rabbitmq:
    host: YOUR_RABBITMQ_ADDRESS # EX) 127.0.0.1
    port: YOUR_RABBITMQ_PORT # EX) 1234
    username: YOUR_RABBITMQ_USERNAME # EX) user
    password: YOUR_RABBITMQ_PASSWORD # EX) password
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://YOUR_POSTGRESQL_URL:PORT/DBNAME?charSet=UTF-8&prepareThreshold=1
    # EX) jdbc:postgresql://127.0.0.1:1234/mydb?charSet=UTF-8&prepareThreshold=1
    username: DB_USERNAME # EX) user
    password: DB_PASSWORD # EX) password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 3
      maximum-pool-size: 20
      pool-name: gdoDBPool_Prod
      auto-commit: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  http:
    multipart:
      max-file-size: 10485760KB # UPLOAD_LIMIT
      max-request-size: 10485760KB # UPLOAD_LIMIT 
server:
  port: 8080 # EX) THE_PORT_OF_WEB_SITE
  context-path: /geodt # EX) THE_CONTEXT_PATH_OF_WEB_SITE
  error:
    whitelabel:
      enabled: false
gitrnd:
  serverhost: PUBLIC_IP_OF_THIS_SERVER_NOT_LOCALHOST # EX) 175.111.222.34
  apache:
    host: 127.0.0.1 #APACHE MUST BE INSTALLED IN THE SAME LOCATION WITH PROD SERVER
    port: APACHE_PORT # EX) 8888
    basedir: gdofiles # THE_DIRECTORY_NAME_OF_UPLOADED_FILE
    basedrive: C # THE_DRIVE_WHERE_USER_UPLOAD_FILE
  rabbitmq:
    exchange: YOUR_RABBITMQ_EXCHANGE # EX) opengds_ex 
    routingKey: YOUR_RABBITMQ_KEY # EX) opengds_k
mybatis:
  config-location: classpath:config/mybatis.xml
  mapper-location: classpath:sql/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true